---
version: '3.9'
services:
  web:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "make quick"
    ports:
      - 8000:8000
    volumes:
      - .:/app
